name: "publish react-native-speed-view"

on:
    release:
        branches: 
            - main

jobs:
    release:
        name: react-native-speed-view
        runs-on: macOS Monterey
        steps:
            - name: 🚀 publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_SECRET}}
